name: CI
on: 
  push:
    branches:
      - main
  pull_request:
    types: [openned, synchronize, reopened]    
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
